# Generated by Django 5.1.7 on 2025-06-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='number_votes',
            new_name='votes',
        ),
    ]
